general {
	hide_cursor = false
	grace = 0
}

background {
	monitor = HDMI-A-2 
	path = ~/Pictures/misc_pictures/forlock_hdmi.png
    fit_mode = contain
	blur_passes = 0
	blur_size = 0
}

label {
	monitor = HDMI-A-2
	text = cmd[update:1000] echo "<span>$(date +'%H:%M:%S')</span>"
	color = rgba(255,255,255,0.4)
	position = 917,-530
	font_size = 15
	font_family = Jersey15
}

input-field {
	monitor = HDMI-A-2
	size = 250,50
	#outer_color = rgba(208,44,51,1)
	#inner_color = rgba(255,255,255,0.15)
	outer_color = rgba(0,0,0,0)
    inner_color = rgba(0,0,0,0)
    font_color = rgba(73, 92, 105,1)
	position = -900,-530
	placeholder_text = 
	capslock_color = rgba(128,128,128,0.1)
	outline_thickness = 0
	dots_size = 0.2
	dots_text_format = *
	rounding = 20
	fade_on_empty = true
	fail_text = ?
	fail_color = rgba(0,0,0,0)
	check_color = rgba(255,255,255,0.4)
	hide_input = false
    hide_input_base_color = rgba(208,44,51,1)
}

splash=false
