wallpaper {
    monitor=eDP-1
    path=/home/saffron/Pictures/forwall/mauser_c96.png
    fit_mode=cover    
}

wallpaper {
    monitor=HDMI-A-2
    path=/home/saffron/Pictures/forwall/mauser_c96.png
    fit_mode=cover
}


splash=false
