#preload = /home/usernorm/Pictures/forwall/space.png  <--OLD HYPRPAPER SYNTAX, <0.8
#wallpaper = eDP-1,/home/usernorm/Pictures/forwall/space.jpg

wallpaper {
    monitor=eDP-1
    path=/home/usernorm/Pictures/forwall/space.png
    fit_mode=cover
}

wallpaper {
    monitor=HDMI-A-1
    path=/home/usernorm/Pictures/forwall/space.png
    fit_mode=cover
}

splash=false
