#For quick access to places

alias l="ls"
alias sl="ls"
alias LS="ls"
alias SL="ls"
alias CD="cd"
alias clera="clear"
alias CLEAR="clear"
alias lsblkk="lsblk"
alias lsbkl="lsblk"
alias to="cd"
alias topy="cd $HOME/Documents/lang/py"
alias tolang="cd $HOME/Documents/lang/"
alias toneb="cd $HOME/Documents/nebula/neb_things"
alias togit="cd $HOME/Documents/misc/git_pushes"
alias toscr="cd $HOME/.scripts"
alias topj="cd $HOME/Documents/.projects"
alias toaur="cd $HOME/Documents/misc/aur_pkgs"
alias tosilo="cd $HOME/.silo"
alias toasg="cd $HOME/Documents/assignments"
alias towork="cd $HOME/Desktop/.work"
alias tocl="cd $HOME/Desktop/.work/saffron_digital/Websites/clients"
alias toedit="cd $HOME/Videos/editing"

#Binaries
alias fdown="aria2c -s 16 -x 16"
alias firelong="$HOME/.scripts/python/firelong.py"
alias m2m="$HOME/.scripts/bash/m2m.sh"
alias nethole="$HOME/.scripts/bash/nethole.sh"
alias vi="vim"
alias termusic="termusic --backend mpv"
alias pahed="~/Desktop/git_clones/animepahe-cli/build/animepahe-cli-beta"
alias onvideo="$HOME/.scripts/bash/video_wall.sh"
alias gtop="amdgpu_top"

#Starting things
alias hx="start-hyprland"
alias powerpm="$HOME/.scripts/bash/power_pm.sh"
alias todo="$HOME/.scripts/bash/todo.sh"

#Others
alias lspwr="fastfetch | grep BAT | cut -d ' ' -f3-"
alias ping_host="ping $(ip route | grep default | cut -d ' ' -f3)"
alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
alias blueup="sudo systemctl start bluetooth;bluetoothctl scan on;bluetoothctl"
alias bluedash="bluetoothctl disconnect;sudo systemctl stop bluetooth"
alias wiup="iwctl station wlan0 scan;sleep 1;iwctl station wlan0 connect myPoco;sleep 1;iw dev"
alias widash="iwctl station wlan0 disconnect;iw dev"
alias tt="kitten icat $HOME/Pictures/misc_pictures/time_table.png"
alias smatrix="cmatrix -sr"
alias whyami="echo -e 'hack'"
